name: Build and Deploy Lambda

env:
    ARTIFACT_NAME: csye6225-serverless-${{ github.sha }}.zip
    AWS_REGION: us-east-1

on:
  pull_request:
    branches: [ main ]

jobs:
  lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build deployment artifact
        run: |
          mkdir serverless_artifact
          zip -r ${{ env.ARTIFACT_NAME }} lambda_function.py
          mv ${{ env.ARTIFACT_NAME }} serverless_artifact/
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy Artifact to S3
        run: | 
            aws s3 sync ./serverless_artifact s3://${{ secrets.S3_SERVERLESS_BUCKET}}
      
      - name: Update lambda function
        run: |
          aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ secrets.S3_CODEDEPLOY_BUCKET }} \
          --s3-key ${{ env.ARTIFACT_NAME }}