name: Build and Deploy Lambda

env:
    ARTIFACT_NAME: csye6225-lambda.zip
    AWS_REGION: us-east-1

on:
  pull_request:
    branches: [ main ]

jobs:
  lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Deployment Artifact
        run: |
            echo 'inside_run'
            pwd
            ls
            mkdir serverless_artifact
            ls
            pwd
            zip -r ${{ env.ARTIFACT_NAME}} ./ 
            pwd
            ls -al
            mv ${{ env.ARTIFACT_NAME}} serverless_artifact/
            ls -al
            pwd
            cd serverless_artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
        
      - name: Copy Artifact to S3
        run: | 
            aws s3 sync ./serverless_artifact s3://${{ secrets.S3_SERVERLESS_BUCKET}}

      - name: Lambda Update Call
        run: |
            aws lambda update-function-code \
            --function-name  csye6225 \
            --zip-file fileb://serverless_artifact/${{ env.ARTIFACT_NAME }}